version: 0.0
os: linux

phases:
  pre_build:
    - location: PreBuildWordPress.sh
      runas: root

  build:
    - location: BuildWordPress.sh
      runas: root

  post_build:
    - location: PostBuildWordPress.sh
      runas: root
