version: 0.0
os: linux

phases:
  pre_build:
    - location: scripts/PreBuildWordPress.sh
      runas: root

  build:
    - location: scripts/BuildWordPress.sh
      runas: root

  post_build:
    - location: scripts/PostBuildWordPress.sh
      runas: root
